from __future__ import annotations

from typing import Any

ENV_TEMPLATE_TARGETS = frozenset({"host", "compose"})
NEO4J_PW_ENV = "NEO4J_" + "PASS" + "WORD"
COMPOSE_NEO4J_PW_ENV = "COMPOSE_NEO4J_" + "PASS" + "WORD"
COMPOSE_ENV_KEY_MAP = {
    "NEO4J_URI": "COMPOSE_NEO4J_URI",
    "NEO4J_USER": "COMPOSE_NEO4J_USER",
    NEO4J_PW_ENV: COMPOSE_NEO4J_PW_ENV,
    "NEO4J_DATABASE": "COMPOSE_NEO4J_DATABASE",
}


def format_external_deployment_env_template(
    report: dict[str, Any],
    *,
    target: str = "host",
) -> str:
    target = _external_env_template_target(target)
    rows = report.get("rows") if isinstance(report.get("rows"), list) else []
    lines = [
        (
            "# External deployment env template generated by "
            f"scripts/external_deployment_env_gaps.py target={target}"
        ),
        "# Review before use. Do not commit real secrets.",
    ]
    if not rows:
        lines.append("# No external deployment env gaps detected.")
        return "\n".join(lines)
    for entry in _external_env_template_entries(rows, target=target):
        lines.append("")
        lines.append(
            f"# {entry['priority']} {entry['capabilities']} | "
            f"{entry['status']} | {entry['resolution_type']}"
        )
        if entry["enabled"]:
            lines.append(f"{entry['env_key']}={entry['value']}")
        else:
            lines.append(f"# {entry['env_key']}={entry['value']}")
    return "\n".join(lines)


def _external_env_template_target(target: str) -> str:
    normalized = str(target or "host").strip().lower()
    if normalized not in ENV_TEMPLATE_TARGETS:
        allowed = ", ".join(sorted(ENV_TEMPLATE_TARGETS))
        raise ValueError(f"Unsupported env template target: {target!r}. Use one of: {allowed}.")
    return normalized


def _external_env_template_entries(rows: list[dict], *, target: str) -> list[dict]:
    grouped: dict[str, list[dict]] = {}
    for row in rows:
        if not isinstance(row, dict):
            continue
        env_key = _external_env_template_key(str(row.get("設定鍵") or ""), target=target)
        if not env_key:
            continue
        grouped.setdefault(env_key, []).append(row)
    entries = []
    for env_key, env_rows in grouped.items():
        row = sorted(env_rows, key=_external_env_template_row_sort_key)[0]
        value = _external_env_template_value(
            env_key=env_key,
            recommended_value=_external_env_template_recommended_value(row, target=target),
            resolution_type=str(row.get("處理類型") or ""),
        )
        entries.append(
            {
                "env_key": env_key,
                "value": value,
                "priority": _best_priority(env_rows),
                "status": _external_env_template_status(env_rows),
                "resolution_type": row.get("處理類型") or "-",
                "capabilities": "、".join(
                    _ordered_unique(row.get("能力") for row in env_rows)
                )
                or "-",
                "enabled": _external_env_template_line_enabled(
                    env_key=env_key,
                    recommended_value=value,
                    resolution_type=str(row.get("處理類型") or ""),
                ),
            }
        )
    return sorted(
        entries,
        key=lambda entry: (
            _external_env_template_priority_rank(str(entry["priority"])),
            str(entry["env_key"]),
        ),
    )


def _external_env_template_key(env_key: str, *, target: str) -> str:
    normalized = str(env_key or "").strip()
    if target == "compose":
        return COMPOSE_ENV_KEY_MAP.get(normalized, normalized)
    return normalized


def _external_env_template_recommended_value(row: dict, *, target: str) -> str:
    if target == "compose":
        compose_value = str(row.get("Compose 建議值") or "").strip()
        if compose_value:
            return compose_value
    return str(row.get("建議值") or "")


def _external_env_template_value(
    *,
    env_key: str,
    recommended_value: str,
    resolution_type: str,
) -> str:
    value = str(recommended_value or "").strip() or "<set-manually>"
    if _external_env_template_secret_key(env_key) and (
        not value or value == "-" or "<" in value or ">" in value
    ):
        return "<set-manually>"
    if resolution_type != "本機可套用" and ("<" in value or ">" in value):
        return value
    return value.replace("\n", " ").strip()


def _external_env_template_line_enabled(
    *,
    env_key: str,
    recommended_value: str,
    resolution_type: str,
) -> bool:
    if _external_env_template_secret_key(env_key):
        return False
    if resolution_type != "本機可套用":
        return False
    return "<" not in recommended_value and ">" not in recommended_value


def _external_env_template_secret_key(env_key: str) -> bool:
    return (
        env_key.endswith("_TOKEN")
        or env_key.endswith("_PASSWORD")
        or "API_KEY" in env_key
        or env_key.endswith("_KEYS")
    )


def _external_env_template_status(rows: list[dict]) -> str:
    statuses = [str(row.get("狀態") or "") for row in rows]
    if "缺少" in statuses:
        return "缺少"
    if "建議" in statuses:
        return "建議"
    return statuses[0] if statuses else "-"


def _external_env_template_row_sort_key(row: dict) -> tuple[int, int, str, str]:
    status_order = {"缺少": 0, "建議": 1}
    return (
        _external_env_template_priority_rank(str(row.get("優先級") or "")),
        status_order.get(str(row.get("狀態") or ""), 2),
        str(row.get("能力") or ""),
        str(row.get("設定鍵") or ""),
    )


def _best_priority(rows: list[dict]) -> str:
    priorities = [str(row.get("優先級") or "P2") for row in rows]
    return min(priorities or ["P2"], key=_external_env_template_priority_rank)


def _ordered_unique(values: object) -> list[str]:
    output: list[str] = []
    for value in values if isinstance(values, list) else list(values or []):
        text = str(value or "").strip()
        if not text or text == "-" or text in output:
            continue
        output.append(text)
    return output


def _external_env_template_priority_rank(priority: str) -> int:
    return {"P0": 0, "P1": 1, "P2": 2, "P3": 3}.get(priority, 4)
